### ISSUE TITLE
--like_run bug

### ISSUE THREAD

**Issue by scemama** [TApplencourt/3dMLBE20_TestSet_CLI#2]
:bug: 

```
$ ./schindler.py list_run --like_run_id=22
Traceback (most recent call last):
  File "./schindler.py", line 45, in <module>
    print_mad_recap(q, order_by=d_arguments["--order_by"])
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/print_util.py", line 96, in print_mad_recap
    for run_id, mad in q.d_mad.iteritems():
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 254, in d_mad
    for run_id, d_ele in self.d_ae_deviation.items():
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 243, in d_ae_deviation
    for run_id, d_ae_run_id in self.d_ae.items():
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 217, in d_ae
    d = self.d_ae_db.copy()
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 188, in d_ae_db
    d = self.db_get("ae_tab")
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 153, in db_get
    l += cond_sql_or("ele_name", self.l_element)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 138, in l_element
    l = cond_sql_or("ele_name", self.l_element_whe_want)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 103, in l_element_whe_want
    l_ele = self.l_element_to_print
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/calc.py", line 125, in l_element_to_print
    l_ele = self.db_list_element(self.d_arguments["--like_run_id"])
  File "/home/scemama/3dMLBE20/3dMLBE20_TestSet_CLI/src/__init__.py", line 287, in lru_cached
    val = f(*arg)
TypeError: db_list_element() takes exactly 2 arguments (1 given)
```

**Comment by TApplencourt** [comment]
#fix
